apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-slack-bot
  namespace: acs-sites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-slack-bot
  template:
    metadata:
      labels:
        app: v-slack-bot
    spec:
      containers:
      - name: v-slack-bot
        image: your-docker-repo/slack-bot:latest
        ports:
        - containerPort: 3000
        env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-bot-secrets
              key: SLACK_WEBHOOK_URL
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: slack-bot-secrets
              key: SLACK_SIGNING_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: v-slack-bot-service
  namespace: acs-sites
spec:
  selector:
    app: v-slack-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
